### ISSUE TITLE
ETG reset mod the gungeon

### ISSUE THREAD

**Issue by AmuroKuroba** [ModTheGungeon/ETGMod.Installer.Core#51]
installed mod the gungeon and when i star it after a few seconds i get loaded in the next chamber but its like hell
![20191004_183331](https://user-images.githubusercontent.com/56168745/66224560-73b2d380-e6d6-11e9-97ed-165da7f3a45c.jpg)

**Comment by katzevans** [comment]
As I recall, this happens whenever you install it to a pirated copy of the game. No?
